name: 'GitHub Org Reminder'
description: 'Publish a message in a channel or send a JSON payload to the Slack Workflow Builder'
author: sonichigo
branding:
  icon: 'at-sign'
  color: 'purple'

inputs:
  # cron-schedule:
  #   description: 'Cron schedule for the workflow'
  #   required: true
  #   default: '0 10 */2 * *' # Every 2 days at 10:00AM UTC
  ORG_NAME:
    description: 'Name of organisation'
    required: true
  SLACK_WEBHOOK_URL:
    description: 'Slack Webhook URL'
    required: true
  GITHUB_TOKEN:
    description: 'Token for the GitHub API'
    required: true
    default: ${{ github.token }}

runs:
  using: 'composite'
  steps:
      - name: Setup GITHUB_PATH for script
        run: |
          echo "${{ github.action_path }}" >> $GITHUB_PATH
          echo "${{ inputs.working-directory }}"
        shell: bash
      - name: Grant permissions
        run: chmod +x ${GITHUB_ACTION_PATH}/app.py
        shell: bash
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          python3 -m pip install --upgrade pip
          pip install PyGithub requests
        shell: bash
      - name: Run reminder script
        env:
          GITHUB_TOKEN: ${{ inputs.GITHUB_TOKEN }}
          ORG_NAME: ${{ inputs.ORG_NAME }}
          SLACK_WEBHOOK_URL: ${{ inputs.SLACK_WEBHOOK_URL }}
        run: |
          python3 ${GITHUB_ACTION_PATH}/app.py
        shell: bash
      - name: Debug environment variables
        run: |
          echo "GITHUB_TOKEN: $GITHUB_TOKEN"
          echo "ORG_NAME: $ORG_NAME"
          echo "SLACK_WEBHOOK_URL: ${SLACK_WEBHOOK_URL:0:10}..."  # Print partial webhook to confirm it’s being passed
        env:
          GITHUB_TOKEN: ${{ inputs.GITHUB_TOKEN }}
          ORG_NAME: ${{ inputs.ORG_NAME }}
          SLACK_WEBHOOK_URL: ${{ inputs.SLACK_WEBHOOK_URL }}
        shell: bash
